### ISSUE TITLE
I tried running nft-toolbox and i couldnt see a start script for development server

### ISSUE THREAD

**Issue by wiredhikari** [scorelab/NFT-Toolbox#28]
On running `npm test` I get:
```
> nft-toolbox@1.0.0 test
> ts-mocha tests/*.spec.ts


Error: Unknown/Unsupported currency
    at getCurrency (/home/hikari/dev/NFT-Toolbox/node_modules/@bundlr-network/client/src/node/currencies/index.ts:60:19)
    at new NodeBundlr (/home/hikari/dev/NFT-Toolbox/node_modules/@bundlr-network/client/src/node/bundlr.ts:24:42)
    at new Arweave (/home/hikari/dev/NFT-Toolbox/src/classes/Arweave.ts:17:21)
    at Object.<anonymous> (/home/hikari/dev/NFT-Toolbox/tests/Arweave.spec.ts:45:24)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module.m._compile (/home/hikari/dev/NFT-Toolbox/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (/home/hikari/dev/NFT-Toolbox/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.exports.requireOrImport (/home/hikari/dev/NFT-Toolbox/node_modules/mocha/lib/nodejs/esm-utils.js:49:16)
    at Object.exports.loadFilesAsync (/home/hikari/dev/NFT-Toolbox/node_modules/mocha/lib/nodejs/esm-utils.js:91:20)
    at singleRun (/home/hikari/dev/NFT-Toolbox/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/home/hikari/dev/NFT-Toolbox/node_modules/mocha/lib/cli/run.js:370:5)
```

**Comment by Akshay-Jagiasi** [comment]
Did you find a solution for it? I'm having the same problem

**Comment by armanthepythonguy** [comment]
Can you assign me this? I would like to work on the project ?

**Comment by wiredhikari** [comment]
> Can you assign me this? I would like to work on the project ?

I have made some progress on it. Till then you can explore other issues
